export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// REQUESTS
export const GET_REQUESTS = "GET_REQUESTS";
export const REQUESTS_LOADING = "REQUESTS_LOADING";
export const REQUESTS_FAILED = "REQUESTS_FAILED";

export const ADD_REQUEST = "ADD_REQUEST";
export const GET_LAST_REQUEST = "GET_LAST_REQUEST";

export const DELETE_REQUEST = 'DELETE_REQUEST';

// ORDERS
export const GET_ORDERS = "GET_ORDERS";
export const ORDERS_LOADING = "ORDERS_LOADING";
export const ORDERS_FAILED = "ORDERS_FAILED";

export const ADD_ORDER = "ADD_ORDER";
export const GET_LAST_ORDER = "GET_LAST_ORDER";

export const GET_FILE_ORDER = "GET_FILE_ORDER";

export const DELETE_ORDER = 'DELETE_ORDER';

// IN STOCK 
export const GET_INSTOCK = "GET_INSTOCK";
export const INSTOCK_LOADING = "INSTOCK_LOADING";
export const INSTOCK_FAILED = "INSTOCK_FAILED";

export const ADD_INSTOCK = "ADD_INSTOCK";
export const GET_LAST_INSTOCK = "GET_LAST_INSTOCK";
export const DELETE_INSTOCK = 'DELETE_INSTOCK';

// OUT OF STOCK 
export const GET_OUTSTOCK = "GET_OUTSTOCK";
export const OUTSTOCK_LOADING = "OUTSTOCK_LOADING";
export const OUTSTOCK_FAILED = "OUTSTOCK_FAILED";

export const ADD_OUTSTOCK = "ADD_OUTSTOCK";
export const GET_LAST_OUTSTOCK = "GET_LAST_OUTSTOCK"; 
